### ISSUE TITLE
Verify that build will fail when recipe is broken

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#106]
As discovered in #105, the build did not fail when it should have. The build should fail in the following circumstances:
- the recipe's `spago.dhall` file doesn't contain a dependency used in the recipe
- the recipe's source code fails to compile
- the recipe (if a web-compatible one) fails to be built

**Comment by milesfrain** [comment]
> the build did not fail when it should have.

I'm not able to reproduce a CI pass with a broken build (due to typed hole, as mentioned in #105). It may have been an older build that ran and got mis-assigned to a different commit. That's happened to me before when adding another commit to the same PR before the previous travis job completed.

Anyway, here's wishlist status:
- [x] the recipe's spago.dhall file doesn't contain a dependency used in the recipe - #112
- [x] the recipe's source code fails to compile - #110 
- [x] the recipe (if a web-compatible one) fails to be built - #113
- [x] **New** - Recipe mismatch in `index.js` is caught - #111

**Comment by JordanMartinez** [comment]
Yeah, the build didn't fail because the `index.js` file was pointing to the wrong recipe's Main output. #111 fixed that, so thanks!
